# Minecraft Server Properties (Render / Cloud Ready)

motd=Render Paper Server
server-port=25565
server-ip=0.0.0.0

online-mode=false
max-players=10

view-distance=4
simulation-distance=4
max-players=5

spawn-protection=0
enable-command-block=true

gamemode=survival
difficulty=easy
pvp=true

allow-nether=true
generate-structures=true
allow-flight=true

level-name=world
level-seed=

enable-rcon=false
enable-query=false

force-gamemode=false
hardcore=false

broadcast-console-to-ops=true
broadcast-rcon-to-ops=false

snooper-enabled=false

# performance / stability
sync-chunk-writes=true
use-native-transport=true

# important for cloud environments
enable-jmx-monitoring=false
prevent-proxy-connections=false
